### ISSUE TITLE
typescript 3.7 有翻译计划？

### ISSUE THREAD

**Issue by lizy0329** [jkchao/typescript-book-chinese#128]

**Comment by jkchao** [comment]
有

**Comment by xie-zhichao** [comment]
啥时候开始？我也想参与

**Comment by kunjiang** [comment]
有点兴趣

**Comment by jkchao** [comment]
这样吧，TypeScript 3.7 的内容部分比较多，按照标题我将他分成了几部分，如果有想参与翻译的部分，可以下面留言：

- [ ] Optional Chaining 和 `--declaration` and `--allowJs`
- [ ] Nullish Coalescing 和 The useDefineForClassFields Flag and The declare Property Modifier
- [ ] Assertion Functions 和  Build-Free Editing with Project References
- [ ] Better Support for never-Returning Functions 和 Uncalled Function Checks
- [ ] (More) Recursive Type Aliases 和 `// @ts-nocheck` in TypeScript Files

参与翻译的方式很简单，fork 此项目，切到 `feat-typescript-3.7` 分支，然后创建自己的分支，往 `feat-typescript-3.7` 提交 PR 就行了。

翻译之前，请阅读 [格式指南](https://github.com/mzlogin/chinese-copywriting-guidelines)。

PS：大家也可参与到校验工作中，有比较好的 TypeScript 英文文章，也可以推荐过来。

一起成长，进步  ❤️

**Comment by ishowman** [comment]
是基于官方英文文档翻译成中文吗

**Comment by jkchao** [comment]
是的，我已经把文件放到了[这里](https://github.com/jkchao/typescript-book-chinese/blob/feat-typescript-3.7/docs/new/typescript-3.7.md)

**Comment by kunjiang** [comment]
第一次参与, 我先选择  `Optional Chaining` 和 `--declaration and --allowJs` 吧!

**Comment by jkchao** [comment]
好，翻译完了，把对应的英文删掉即可

**Comment by xie-zhichao** [comment]
我也是第一次翻译，我选 `Assertion Functions` 和 `Build-Free Editing with Project References`。

**Comment by jkchao** [comment]
@xie-zhichao 好的

**Comment by xie-zhichao** [comment]
我的翻译已提交

**Comment by jkchao** [comment]
好的，我这周周末看一下，然后发布上去
