### ISSUE TITLE
静态网站是用什么生成的？

### ISSUE THREAD

**Issue by BryanAdamss** [jkchao/typescript-book-chinese#157]
你好，我有在阅读你翻译的书；
我想问下，你这个静态网站
https://jkchao.github.io/typescript-book-chinese/
是如何生成的？
有关键字吗？因为我最近也想弄一个类似的翻译项目!

**Comment by justjavac** [comment]
浓浓的 vuepress 风

**Comment by BryanAdamss** [comment]
@justjavac 嗯，已经找到了；正在实践中😁
