### ISSUE TITLE
union 转 intersection 例子

### ISSUE THREAD

**Issue by wQueryLoveMm** [jkchao/typescript-book-chinese#159]
string & number 最后会被推导为 never 类型

![image](https://user-images.githubusercontent.com/18161150/73326839-84dbad80-428e-11ea-8213-7afa2f976777.png)

tsc --version
Version 3.7.4

**Comment by jkchao** [comment]
TypeScript 版本升级以后，就不能推导出 string & number 了，我把例子代码更正一下

**Comment by wQueryLoveMm** [comment]
对的，看到这里，试验了下，结果不一样，感谢修改。
