### ISSUE TITLE
文案是不是错了？

### ISSUE THREAD

**Issue by l408012828** [jkchao/typescript-book-chinese#198]
- https://jkchao.github.io/typescript-book-chinese/#why

- 文字【希望你在翻译或者 PR 之前，阅读中文文章排版指**北**】最后一个字是 【南】吧

**Comment by baurine** [comment]
「中文文案排版指北」- https://github.com/mzlogin/chinese-copywriting-guidelines

哈哈，跟「指南」一个意思，只不过换个说法而已，带点幽默。

**Comment by l408012828** [comment]
哈哈哈 不好意思&nbsp;&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sparkle"<notifications@github.com&gt;; 
发送时间: 2020年6月12日(星期五) 下午2:15
收件人: "jkchao/typescript-book-chinese"<typescript-book-chinese@noreply.github.com&gt;; 
抄送: "夜雨星空"<807274347@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jkchao/typescript-book-chinese] 文案是不是错了？ (#198)





 
「中文文案排版指北」- https://github.com/mzlogin/chinese-copywriting-guidelines
 
哈哈，跟「指南」一个意思，只不过换个说法而已，带点幽默。
