### ISSUE TITLE
类可以实现接口 是不是写的有点问题

### ISSUE THREAD

**Issue by joe0110** [jkchao/typescript-book-chinese#6]
// 工具中提示 缺少分号，看了下官网 好像是要写分号的，刚学也不是很懂
interface IPoint {
  x: number,    //是不是应该是 ;
  y: number
}

class MyPoint implements IPoint {
  x: number， //是不是应该是 ;
  y: number // Same as Point
}

**Comment by joe0110** [comment]
建议 作者把写的案例，放到编辑器里跑下(萌新 也不知道对不对)

**Comment by jkchao** [comment]
@joe0110 逗号，分号，或者是不写都是可以的，我习惯了写逗号，推荐是写分号。

**Comment by joe0110** [comment]
对的，谢谢了，大佬有时间 写个简单的 小程序demo么，最近在开发小程序，但是不知道怎么下手(最近在看你写的文章)

**Comment by jkchao** [comment]
@joe0110 最近可能会比较忙，等过一段时间。😂

**Comment by joe0110** [comment]
作者麻烦删下这条无关的issues （还有之前的一条，谢谢了）
