### ISSUE TITLE
概览中的null 和undefined 例子编译会出现问题

### ISSUE THREAD

**Issue by w1301625107** [jkchao/typescript-book-chinese#78]
![image](https://user-images.githubusercontent.com/29950066/53161053-27fa6080-3604-11e9-8962-6fa580ca88cf.png)
tempCodeRunnerFile.ts(5,1): error TS2322: Type 'null' is not assignable to type 'number'.
tempCodeRunnerFile.ts(6,1): error TS2322: Type 'undefined' is not assignable to type 'string'.

**Comment by jkchao** [comment]
`strictNullChecks: false`的时候是可以的。
看来有必要加上一个 `strictNullChecks: false` 的注释。
